Basic_App/urls.py
from django.urls import path
from Basic_App import views

app_name='Basic_App'
urlpatterns=[
path('',views.indexlist.as_view(),name="index"),
path('shop/',views.Shoplist.as_view(),name="shop"),
path('checkout/',views.checkout,name="checkout"),
path('product-details/<int:pk>/',views.indexDetailView.as_view(),name="product"),
path('shop-product-details/<int:pk>/',views.indexDetailView.as_view(),name="shop_product"),
path('cart/<int:pk>/',views.CartDetailView.as_view(),name='cart'),
path('carts/<int:pk>/',views.indexCartDetailView.as_view(),name='carttt'),
path('a/',views.indsercelist.as_view(),name='q'),
]

online_shoping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Basic_App.urls',namespace='Basic_App')),



]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Basic_App/models.py
from django.db import models


# Create your models here.

class home(models.Model):
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    price=models.FloatField()
    image=models.ImageField(upload_to='media/home')
    details=models.TextField()
    posted_on=models.DateTimeField(null=True,blank=True)


    def get_absolute_url(self):
        return reverse('Basic_App:product', kwargs={'pk': self.pk})
    def image_url(self):
        if self.image and hasattr(self.image,'url'):
            return self.image.url
    def __str__(self):
        return self.title
class Categori(models.Model):
    Category=models.CharField(max_length=200)


    def __str__(self):
        return self.Category


class Shop(models.Model):
    Category=models.CharField(max_length=200)
    title=models.ForeignKey('home',on_delete=models.CASCADE)
    price=models.FloatField()
    image=models.ImageField(upload_to='media/shop')
    details=models.TextField()
    posted_on=models.DateTimeField(null=True,blank=True)


    def get_absolute_url(self):
        return reverse('Basic_App:shopproduct', kwargs={'pk': self.pk})


    def image_url(self):
        if self.image and hasattr(self.image,'url'):
            return self.image.url
    def __str__(self):
        return self.Category
#class Product(models.Model):

class Checkout(models.Model):
    fname=models.CharField(max_length=100)
    lname=models.CharField(max_length=100)
    c_name=models.CharField(max_length=100)
    email=models.EmailField()
    d=[("1","Bangladesh"),
       ("2","India"),
	   ("3","Mayanmar"),
	   ("4","Soudi Arabia"),
	   ("5","Pakistan"),
	   ("6","Canada"),
	   ("7","Malaysia"),
	   ("8","China"),
	   ("9","US"),
	   ("10","UK"),
       ('11','Other'),
       ]
    states=models.CharField(max_length=200,choices=d)
    address=models.CharField(max_length=200)
    town=models.CharField(max_length=200)
    zipcode=models.PositiveIntegerField()
    phone_number=models.IntegerField()
    comment=models.TextField()

    def __str__(self):
        return self.email

Basic_App/views.py
from django.shortcuts import render,redirect
from django.views.generic import (
TemplateView,ListView,CreateView,DeleteView,DetailView,UpdateView)
from Basic_App.models import home,Shop,Checkout,Categori
from Basic_App.form import Checkoutform
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.
class indexlist(ListView):

    model=home

    template_name='indexhelper.html'
    context_object_name='pos'
    paginate_by = 1
    queryset = home.objects.all()


class indexDetailView(DetailView):
    model=home
    queryset = home.objects.all()
    template_name='product-details.html'
    context_object_name='pos'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['author-list'] = home.objects.all()
        return context
class indsercelist(ListView):

    model=home
    queryset = home.objects.all()
    template_name='indexhelper.html'
    context_object_name='pos'
    def get_queryset(self):
        search=self.request.GET.get('q')
        if search:
            pos=self.queryset.filter(
        Q(title__icontains=search)|Q(price__icontains=search)|Q(posted_on__icontains=search)

            )
        else:
            pos = self.model.objects.none()
        return pos


class Shoplist(ListView):

    paginate_by = 3
    template_name='shop.html'
    model=Shop
    def get_queryset(self):
        search=self.request.GET.get('q')
        if search:
            pos=self.model.objects.filter(
            Q(Category__icontains=search)

            )
        else:
            pos= self.model.objects.none()
        return pos

    def get_context_data(self, **kwargs):
        context = super(Shoplist, self).get_context_data(**kwargs)
        context['pos'] = Shop.objects.order_by('posted_on')
        context['postt']=Categori.objects.all()

        return context

class ShopDetailView(DetailView):
    model=Shop
    queryset = Shop.objects.all()
    template_name='shop-product-details.html'
    context_object_name='pos'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['author-list'] = home.objects.all()
        return context


class CartDetailView(DetailView):
    model=Shop
    queryset = Shop.objects.all()
    template_name='cart.html'
    context_object_name='pos'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['author-list'] = home.objects.all()
        return context
class indexCartDetailView(DetailView):
    model=home
    queryset = home.objects.all()
    template_name='cart.html'
    context_object_name='pos'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['author-list'] = home.objects.all()
        return context
def checkout(request):
    if request.method=='POST':
        form=Checkoutform(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('Basic_App:index')
    else:
        form=Checkoutform()
    return render(request,"checkout.html",{'form':form})

def shop(request):
    return render(request,"shop.html")

templates/cart.html
{%extends  'index.html'%}
{%load static%}

{%block content%}

        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="cart-title mt-50">
                            <h2>Shopping Cart</h2>
                        </div>

                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th>Images</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="cart_product_img">
                                            <a href="#"><img src="{{pos.image_url|default_if_none:'#'}}" alt="Product"></a>
                                        </td>
                                        <td class="cart_product_desc">
                                            <h5>{{pos.title}}</h5>
                                        </td>
                                        <td class="price">
                                            <span>${{pos.price}}</span>
                                        </td>
                                        <td class="qty">
                                            <div class="qty-btn d-flex">
                                                <p>Qty</p>
                                                <div class="quantity">
                                                    <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) effect.value--;return false;"><i class="fa fa-minus" aria-hidden="true"></i></span>
                                                    <input type="number" class="qty-text" id="qty" step="1" min="1" max="300" name="quantity" value="1">
                                                    <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>subtotal:</span>

                                 <span>${{pos.price}}</span></li>
                                <li><span>delivery:</span> <span>10</span></li>
                                <li><span>total:</span> <span>${{pos.price}}</span></li>
                            </ul>
                            <div class="cart-btn mt-100">
                                <a href="{%url 'Basic_App:checkout' %}" class="btn amado-btn w-100">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {%endblock%}
    <!-- ##### Main Content Wrapper End ##### -->

templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>{%block title%}{%endblock%}</title>

    <!-- Favicon  -->
    <link rel="icon" href="{%static 'img/core-img/favicon.ico' %}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{%static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{%static 'css/style.css' %}">

</head>

<body>

    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">


                      <form action="" method="GET">
                          <input type="search" name="q"  placeholder="Type your keyword..." role="search">
                          <button type="submit"><img src="{%static 'img/core-img/search.png' }" alt=""></button>
                      </form>
    <!-- Search Wrapper Area End -->
  </div>
</div>
</div>
</div>
</div>

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href=" "><img src="{static 'img/core-img/logo.png' %}" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href=""><img src="{%static 'img/core-img/logo.png' %}" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li class="active"><a href="{%url 'Basic_App:index' %}">Home</a></li>
                    <li><a href="{%url 'Basic_App:shop'%}">Shop</a></li>


                    <li><a href="{%url 'Basic_App:checkout'%}">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
            <a href="#" class="fav-nav"><img src="{%static 'img/core-img/favorites.png' %}" alt=""> Favourite</a>
            <a href="#" class="search-nav"><img src="{%static 'img/core-img/search.png' %}" alt=""> Search</a>
{%block paginator%}
{%endblock%}

            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->

        <!-- Product Catagories Area Start -->
        <div class="products-catagories-area clearfix">
            <div class="amado-pro-catagory clearfix">

                <!-- Single Catagory -->

   {%block content%}

      {%endblock%}
                <!-- Single Catagory -->


                <!-- Single Catagory -->

                <!-- Single Catagory -->

            </div>
        </div>
        <!-- Product Catagories Area End -->
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    <!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href=""><img src="{%static 'img/core-img/logo2.png' %}" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="shop">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="product-details">Product</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link" href="checkout">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="{%static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{%static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{%static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{%static 'js/active.js' %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</body>

</html>

templates/indexhelper.html
{%extends  'index.html'%}
{%load static%}
{%block title%}Home online shop{%endblock%}

{%block content%}
{%for aaa in pos %}
<div class="single-products-catagory clearfix">
    <a href="{%url 'Basic_App:product' pk=aaa.pk%}">
        <img src="{{aaa.image_url|default_if_none:'#'}}" alt="">
        <!-- Hover Content -->
        <div class="hover-content">
            <div class="line"></div>
            <p>From ${{aaa.price}}</p>
            <h4>{{aaa.title}}</h4>
        </div>
    </a>
</div>
{%endfor%}
{%endblock%}
{%block paginator%}
<div class="paginator">
  <ul  class="pagination justify-content-center" style="margin:20px 0">
  {%if page_obj.has_previous%}

  <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
  {%endif%}
{%for num in paginator.page_range%}
{%if page_obj.number == num %}
<li class="page-item"><a class="page-link" href="?page={{num}}"><strong>{{num}}</strong></a></li>
{%elif num > data.number|add:'-3' and num < data.number|add:'3'%}
<li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
    {%endif%}
{%endfor%}

{%if page_obj.has_next%}
<li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>


{%endif%}
</ul>
</div>
{%endblock%}

templates/product-details.html
{%extends  'index.html'%}
{%load static%}

{%block content%}
        <!-- Header Area End -->

        <!-- Product Details Area Start -->
        <div class="single-product-area section-padding-100 clearfix">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb mt-50">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Furniture</a></li>
                                <li class="breadcrumb-item"><a href="#">Chairs</a></li>
                                <li class="breadcrumb-item active" aria-current="page">white modern chair</li>
                            </ol>
                        </nav>
                    </div>
                </div>

                <div class="row">

                    <div class="col-12 col-lg-7">
                        <div class="single_product_thumb">
                            <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li class="active" data-target="#product_details_slider" data-slide-to="0" style="background-image: url({{pos.image_url|default_if_none:'#'}});">

                                </ol>
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <a class="gallery_img" href="{{pos.image_url|default_if_none:'#'}}">
                                            <img class="d-block w-100" src="{{pos.image_url|default_if_none:'#'}}" alt="First slide">
                                        </a>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-5">
                        <div class="single_product_desc">
                            <!-- Product Meta Data -->
                            <div class="product-meta-data">
                                <div class="line"></div>
                                <p class="product-price">${{pos.price}}</p>
                                <a href="#">
                                    <h6>{{pos.title}}</h6>
                                </a>
                                <!-- Ratings & Review -->
                                <div class="ratings-review mb-15 d-flex align-items-center justify-content-between">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                    <div class="review">
                                        <a href="#">Write A Review</a>
                                    </div>
                                </div>
                                <!-- Avaiable -->
                                <p class="avaibility"><i class="fa fa-circle"></i> In Stock</p>
                            </div>

                            <div class="short_overview my-5">
                                <p>{{pos.details}}</p>
                            </div>

                            <!-- Add to Cart Form -->

                               <a class="cart clearfix" href="{%url 'Basic_App:carttt' pk=pos.pk%}">
                                <button type="submit" name="addtocart" value="5" class="btn amado-btn">Add to cart</button></a>


                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Product Details Area End -->

    <!-- ##### Main Content Wrapper End ##### -->

    <!-- ##### Newsletter Area Start ##### -->
{%endblock%}

templates/shop.html
{%extends  'index.html'%}
{%load static%}
{%block title%}Shoping{%endblock%}

{%block content%}


    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->

        <!-- Header Area End -->


        <div class="shop_sidebar_area">

            <!-- ##### Single Widget ##### -->
            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Catagories</h6>

                <!--  Catagories  -->

                <div class="catagories-menu">

                    <ul>
                        {%for p in postt%}
                        <li class="active"><a href="{%url 'Basic_App:shop'%}?q={{p.Category}}">{{p.Category}}</a></li>
                        {%endfor%}

                    </ul>

                </div>

            </div>

            <!-- ##### Single Widget ##### -->
            <div class="widget brands mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Brands</h6>

                <div class="widget-desc">
                    <!-- Single Form Check -->
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="amado">
                        <label class="form-check-label" for="amado">Amado</label>
                    </div>


                            </div>
            </div>



        </div>

        <div class="amado_product_area section-padding-100">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <div class="product-topbar d-xl-flex align-items-end justify-content-between">
                            <!-- Total Products -->

                            <!-- Sorting -->
                            <div class="product-sorting d-flex">
                                <div class="sort-by-date d-flex align-items-center mr-15">
                                    <p>Sort by</p>
                                    <form action="#" method="get">
                                        <select name="select" id="sortBydate">
                                            <option value="value">Date</option>
                                            <option value="value">Newest</option>
                                            <option value="value">Popular</option>
                                        </select>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
  {%for p in pos%}
                    <!-- Single Product Area -->
                    <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                        <div class="single-product-wrapper">
                            <!-- Product Image -->
                            <div class="product-img">
                                <img src="{{p.image_url|default_if_none:'#'}}" alt="">
                                <!-- Hover Thumb -->
                                <img class="hover-img" src="img/product-img/product2.jpg" alt="">
                            </div>

                            <!-- Product Description -->
                            <div class="product-description d-flex align-items-center justify-content-between">
                                <!-- Product Meta Data -->
                                <div class="product-meta-data">
                                    <div class="line"></div>
                                    <p class="product-price">${{p.price}}</p>
                                    <a href="{%url 'Basic_App:shop_product' pk=p.pk %}">
                                        <h6>{{p.title}}</h6>
                                    </a>
                                </div>
                                <!-- Ratings & Cart -->
                                <div class="ratings-cart text-right">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                    <div class="cart">
                                        <a href="{%url 'Basic_App:cart' pk=p.pk%}" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="{%static 'img/core-img/cart.png' %}" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>




                                <!-- Ratings & Cart -->
{%endfor%}
                            </div>

                        </div>
                    </div>

                  </div>


    {%endblock%}



    {%block paginator%}
    <div class="paginator">
      <ul  class="pagination justify-content-center" style="margin:20px 0">
      {%if page_obj.has_previous%}

      <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
      {%endif%}
    {%for num in paginator.page_range%}
    {%if page_obj.number == num %}
    <li class="page-item"><a class="page-link" href="?page={{num}}"><strong>{{num}}</strong></a></li>
    {%elif num > data.number|add:'-3' and num < data.number|add:'3'%}
    <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
        {%endif%}
    {%endfor%}

    {%if page_obj.has_next%}
    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>


    {%endif%}
    </ul>
    </div>
    {%endblock%}